/*
  Warnings:

  - The values [BACHARELADO_ED_FISICA] on the enum `CourseName` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "CourseName_new" AS ENUM ('TECNICO_AGROPECUARIA', 'TECNICO_AGROINDUSTRIA', 'TECNICO_MEIO_AMBIENTE', 'TECNICO_SUBSEQUENTE_AGROPECUARIA', 'TECNICO_SUBSEQUENTE_INFORMATICA', 'TECNICO_SUBSEQUENTE_ALIMENTOS', 'BACHARELADO_SISTEMA_DE_INFORMACAO', 'BACHARELADO_LIBRAS', 'BACHARELADO_EDUCACAO_FISICA', 'POS_ENSINO_DE_CIENCIAS_NATURAIS_E_MATEMATICA', 'POS_LEITURA_E_PRODUCAO_TEXTUAL_APLICADAS_A_EJA');
ALTER TABLE "Course" ALTER COLUMN "name" TYPE "CourseName_new" USING ("name"::text::"CourseName_new");
ALTER TYPE "CourseName" RENAME TO "CourseName_old";
ALTER TYPE "CourseName_new" RENAME TO "CourseName";
DROP TYPE "CourseName_old";
COMMIT;
